 max_revenue = {"revenue": 0}
  max_sales = {"car" : "NO","total sales": 0}
  popular_year = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    if item["total_sales"] > max_sales["total sales"]:
      max_sales["total sales"] = item["total_sales"]
      max_sales["car"] = item["car"]
    # TODO: also handle most popular car_year
    popular_year[item["car"]["car_year"]] = popular_year.get(item["car"]["car_year"],0)+ item["total_sales"]

  pyear = max(popular_year, key = popular_year.get)

  summary = [
    "The {} generated the most revenue: ${}".format(
      format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(
         format_car(max_sales["car"]), max_sales["total sales"]),
      "The most popular year was {} with {} sales.".format(
      pyear,popular_year[pyear]),
  ]